import "./globals.scss";
import "react-toastify/dist/ReactToastify.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import AxiosProvider from "@/contexts/AxiosContext";
import AuthProvider from "@/contexts/AuthContext";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import { config } from "@fortawesome/fontawesome-svg-core";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AxiosProvider>
          <AuthProvider>{children}</AuthProvider>
        </AxiosProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
