import "./globals.scss";
import "react-toastify/dist/ReactToastify.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import AxiosProvider from "@/contexts/AxiosProvider";
import { Inter } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import SocketProvider from "@/contexts/SocketProvider";
import ThemeProvider from "@/contexts/ThemeProvider";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AxiosProvider>
          <SocketProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </SocketProvider>
        </AxiosProvider>
      </body>
    </html>
  );
}
